print()   
print("PANTUN 1")
print("Jalan-Jalan ke Pulau Seberang")
print("Jangan Lupa Membeli Kue Bolu")
print("Kalau Mau Hidup Tetap Tenang")
print("Hendaklah Pikiran Positif Selalu")
print()
print("PANTUN 2")
print("Ke Rumah Anton Membeli Gulali")
print("Melihat Cermin Langsung Berkaca")
print("Bahasa Python Simple Sekali")
print("Udah Gratis Juga Mudah Dibaca")
print()
print("PANTUN 3")
print("Pergi ke Toko Membeli Sajadah")
print("Pulangnya Mampir ke Rumah Teman")
print("Langit Malam Sangatlah Indah")
print("Bertabur Bintang Cahaya Menawan")
print()
# ini adalah komentar
# aku sedang belajar dasar pemrograman python